### ISSUE TITLE
.appveyor

### ISSUE THREAD

**Issue by AlexGipp** [guitarrapc/SkiaSharp.QrCode#11]
I dont know if this is an issue but im gonna report it anyway.

Your nuget api key is exposed in the appveyor.yml file.

**Comment by guitarrapc** [comment]
I cant get what you mean. I suppose nuget key in appveyor.yml is encrypted, but is not?

**Comment by AlexGipp** [comment]
Like i am not sure if this is an actual issue, but if this: 
`uLbsU9zHQNqoFLVXzPqk5QyoKVXu/vj6LIZEkCjqm5h+MPXR/2bQG0p8bjnnE0Oz`
is your actual token then you should really hide that.
(Just a suggestion though 😄)

**Comment by guitarrapc** [comment]
Thank you for your kindness, however this is encrypted token as https://www.appveyor.com/docs/how-to/secure-files/ describe.
