### ISSUE TITLE
Cake

### ISSUE THREAD

**Issue by AlexGipp** [guitarrapc/SkiaSharp.QrCode#14]
Do you think it would be useful to add cake next? 
(To build the nuget package and run tests in the future, maybe check the code, etc)

This is cake in case you dont know what it is:
https://cakebuild.net/

**Comment by guitarrapc** [comment]
Thnak you for the suggestion, but cake is too match for just an CI. I will add GitHub Actions workflow, which I used to CI .NET Core Libs on my other repos. Plz wait a moment.
