### ISSUE TITLE
Assembly signing not present, causes failure on ASP.NET

### ISSUE THREAD

**Issue by monkeycoder99** [guitarrapc/SkiaSharp.QrCode#31]
ASP.NET-based applications typically require assemblies to be signed or it fails to load them with the message "Could not load file or assembly. A strongly-named assembly is required". The solution is rather simple as documented here: https://medium.com/@ShaoWenbinSaleh/fix-error-a-strongly-named-assembly-is-required-in-visual-studio-9cad3e7327dd.

**Comment by guitarrapc** [comment]
I've released 0.6.0 and it's assembly is signed.
