### ISSUE TITLE
I added a logo and text to the QR code, but they look very blurry.

### ISSUE THREAD

**Issue by ZhangYiQiu** [guitarrapc/SkiaSharp.QrCode#56]
Are others experiencing this issue?

**Comment by guitarrapc** [comment]
Could you provide any reproducable code?

**Comment by ZhangYiQiu** [comment]
> Could you provide any reproducable code?

Sorry, it's my problem. I used ci this code in telegrambot and the image was compressed by telegram, resulting in reduced clarity

**Comment by ZhangYiQiu** [comment]
Thank you very much
