### ISSUE TITLE
update SkiaSharp ？

### ISSUE THREAD

**Issue by mrt3389** [guitarrapc/SkiaSharp.QrCode#66]
"The SkiaSharp version needs to be upgraded to a version >= 2.0.0 and less than 2.88.6 as there are critical vulnerabilities in versions within this range."

**Comment by guitarrapc** [comment]
@mrt3389 thank you for creating issue. I've released v0.7.0 which updated SkiaSharp dependencies to latest 2.88.6.

> https://www.nuget.org/packages/SkiaSharp.QrCode

Can you try it?
