### ISSUE TITLE
Can the white margin of the QR code be set?

### ISSUE THREAD

**Issue by t-jian** [guitarrapc/SkiaSharp.QrCode#76]
I want to make the red mark smaller, how to set it?
![image](https://github.com/guitarrapc/SkiaSharp.QrCode/assets/23479290/bbe8453f-635c-4668-8a3f-c327eb13c00b)

**Comment by guitarrapc** [comment]
dup https://github.com/guitarrapc/SkiaSharp.QrCode/issues/36

Use `quiteZoneSize` parameter to control marked place. Less than 4 will make it smaller.
Here's sample code.

```csharp
    var content = "testtesttest";
    using var generator = new QRCodeGenerator();
    var qr = generator.CreateQrCode(content, ECCLevel.L, quietZoneSize: 1); // default 4
```

**Comment by t-jian** [comment]
Thank you. 
I have a suggestion. You are advised to mark it in the document .
