### ISSUE TITLE
PNG Output creates transparent Image (alpha = 0)

### ISSUE THREAD

**Issue by codebaard** [guitarrapc/SkiaSharp.QrCode#8]
When I create a PNG-Output, I'll get a PNG with alpha = 0 (transparent). Is there a way to set alpha = 1 (fully opaque)?

Also: If just use the option JPEG Output, I get a fully black Image. Is this an actual Issue or supposed to be that way?

Thanks in Advance.

**Comment by jvitkauskas** [comment]
My solution:

charp```public byte[] GenerateQrCode(string content)
        {
            using (var generator = new QRCodeGenerator())
            {
                var qr = generator.CreateQrCode(content, ECCLevel.L);
                
                var info = new SKImageInfo(200, 200);
                using (var surface = SKSurface.Create(info))
                {
                    var canvas = surface.Canvas;
                    canvas.Clear(SKColors.White);
                    using (QRCodeRenderer qrCodeRenderer = new QRCodeRenderer())
                    {
                        SKRect area = SKRect.Create(0.0f, 0.0f, info.Width, info.Height);
                        qrCodeRenderer.Render(canvas, area, qr);
                    }
                    
                    using (var image = surface.Snapshot())
                    using (var data = image.Encode(SKEncodedImageFormat.Png, 100))
                    using (var stream = new MemoryStream())
                    {
                        data.SaveTo(stream);
                        
                        return stream.ToArray();
                    }
                }
            }
        }```

**Comment by codebaard** [comment]
I actually reverted back to system.drawing for other reasons and solved my Issues with docker. So I'm actually already fine. 
Thanks for the effort anyway :-)
